/**
 * Define action types here
 * 
 * Action Types are string constants to indentify different actions
 * in the reducers of Redux Store
 */

export const UPDATES_LOADING = 'UPDATES_LOADING';
export const UPDATES_FAILED = 'UPDATES_FAILED';
export const ADD_UPDATES = 'ADD_UPDATES';

export const LOGIN = 'LOGIN';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOAD_KEY = 'LOAD_KEY';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_ACHIEVEMENTS = 'LOAD_PROFILE_ACHIEVEMENTS';
export const LOAD_PROFILE_PROJECTS = 'LOAD_PROFILE_PROJECTS';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

export const LOAD_PROFESSORS_LIST = 'LOAD_PROFESSORS_LIST';
export const PROFESSORS_LIST_LOADING = 'PROFESSORS_LIST_LOADING';
export const LOAD_STUDENTS_LIST = 'LOAD_STUDENTS_LIST';
export const STUDENTS_LIST_LOADING = 'STUDENTS_LIST_LOADING';
export const LOAD_INSTITUTES_LIST = 'LOAD_INSTITUTES_LIST';
export const INSTITUTES_LIST_LOADING = 'INSTITUTES_LIST_LOADING';
export const LOAD_TAGS_LIST = 'LOAD_TAGS_LIST';
export const TAGS_LIST_LOADING = 'TAGS_LIST_LOADING';
export const ADD_TAG_LIST = 'ADD_TAG_LIST';

export const ADD_ACHIEVEMENT_POSTING = 'ADD_ACHIEVEMENT_POSTING';
export const ADD_ACHIEVEMENT_POSTING_ERROR = 'ADD_ACHIEVEMENT_POSTING_ERROR';
export const ADD_ACHIEVEMENT_POSTING_SUCCESS = 'ADD_ACHIEVEMENT_POSTING_SUCCESS';

export const ADD_PROJECT_POSTING = 'ADD_PROJECT_POSTING';
export const ADD_PROJECT_POSTING_ERROR = 'ADD_PROJECT_POSTING_ERROR';
export const ADD_PROJECT_POSTING_SUCCESS = 'ADD_PROJECT_POSTING_SUCCESS';

export const ADD_PENDING_ACHIEVEMENTS = 'ADD_PENDING_ACHIEVEMENTS';
export const PENDING_ACHIEVEMENTS_LOADING = 'PENDING_ACHIEVEMENTS_LOADING';
export const PENDING_ACHIEVEMENTS_LOADING_ERROR = 'PENDING_ACHIEVEMENTS_LOADING_ERROR';

export const ADD_PENDING_PROJECTS = 'ADD_PENDING_PROJECTS';
export const PENDING_PROJECTS_LOADING = 'PENDING_PROJECTS_LOADING';
export const PENDING_PROJECTS_LOADING_ERROR = 'PENDING_PROJECTS_LOADING_ERROR';

export const PROJECT_APPROVING = 'PROJECT_APPROVING';
export const PROJECT_REJECTING = 'PROJECT_REJECTING';
export const PROJECT_APPROVED = 'PROJECT_APPROVED';
export const PROJECT_REJECTED = 'PROJECT_REJECTED';
export const PROJECT_ERROR = 'PROJECT_ERROR';

